---
- name: windows user add
  hosts: win
  vars:
    usr_groups: "Users"
    usr_name: "test111"
    usr_password:"Wlsldks123!"
    
  tasks:
    - name: create local user
      ansible.windows.win_user:
        name: "{{ usr_name }}"
        password: "{{ usr_password }}"
        groups: "{{ usr_groups }}"
        update_password: on_create
        password_expired: true
