---
- name: windows user add
  hosts: win
  vars:
    usr_name: 'example'
    usr_password: 'Wlsldks123!'
    usr_groups: "Users"
  tasks:
    - name: Ensure user bob is present
      win_user:
        name: bob
        password: B0bP4ssw0rd
        state: present
        groups:
         - Users
